return {
    Music = 'a',
    FullStar = 'b',
    EmptyStar = 'c',
    HalfFullStar = 'd',
    HalfEmptyStar = 'e',
    Times = 'f',
    Minus = 'g',
    Information = 'h',
    House = 'i',
    SounOff = 'j',
    SoundOn = 'k',
    Cog = 'l',
    Play = 'm',
    Quit = 'n',
    Opera = 'o',
    FKey = '?',
    GKey = 'G',
    QuarterNote = 'q',
    WholeNote = 'w',
    BraceRight = '}',
    Eacute = '>',
    Droplet = 'v',
    Spinner = 'p',
    VolumeUte='r'
}