name: Validate lua code

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y luajit lua-check lua-busted
    - name: Run luacheck
      run: luacheck .
    - name: Run unit tests
      run: busted -m=./?/init.lua
    - name: Install stylua
      run: cargo install stylua
    - name: Check style
      run: stylua -c src/**/*.lua
